run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - revive
    - misspell
    - gofmt
    - goimports
    - gocritic

linters-settings:
  revive:
    rules:
      - name: exported
  gocritic:
    enabled-tags:
      - diagnostic
      - style
